[package]
name = "terminal_code"
version = "0.1.0"
edition = "2024"

[dependencies]
ron = "0.12.2"
toml = "1.1.6"
dirs = "7.0.0"
trash = "5.2.9"
regex = "1.13.1"
base64 = "0.23.1"
ignore = "0.4.33"
futures = "0.3.34"
ratatui = "0.30.2"
renamore = "0.3.2"
thiserror = "2.0.21"
grep-regex = "0.1.14"
grep-matcher = "0.1.9"
unicode-width = "0.2.2"
grep-searcher = "0.1.17"
terminal-colorsaurus = "1.0.3"
unicode-segmentation = "1.13.3"
notify-debouncer-mini = "0.7.0"
serde = { version = "1.0.229", features = ["derive"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
tree-sitter = "0.27.1"
tree-sitter-rust = "0.24.2"
tree-sitter-toml-ng = "0.7.0"
tree-sitter-json = "0.24.8"
tree-sitter-md = "0.5.3"
tree-sitter-nix = "0.3.0"
ropey = { version = "1.6.1", default-features = false, features = ["simd"] }
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "sync", "time"] }
arboard = { version = "3.6.1", default-features = false, features = ["wayland-data-control"] }

[dev-dependencies]
proptest = "1.11.0"
tempfile = "3.27.0"
